#!/bin/bash
buckets=$(aws s3api list-buckets --query 'Buckets[*].Name' --output text) 
for bucket in $buckets; do   
  if ! aws s3 ls s3://$bucket; then
     echo "Deleting unused bucket: $bucket" 
     aws s3 rb s3://$bucket --force  
  fi 
done 
