#!/bin/bash
aws ec2 run-instances \
  --image-id ami-12345678 \ 
  --count 1 \
  --instance-type t2.micro \ 
  --key-name my-key-pair \ 
  --security-group-ids sg-12345678 \ 
  --subnet-id subnet-12345678
echo "EC2 instance laun
